/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ConexionMySQL;
import Controlador.ControladorCanciones;
import Modelo.Cancion;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MEDAC
 */
public class VentanaLista extends javax.swing.JFrame {

    LoginPage paginaLog;
    private final ConexionMySQL conexion;
    private final ControladorCanciones controlador;
    private VentanaReproducir ventanaReproducir;

    /**
     * Creates new form VentanaReproduccion
     */
    public VentanaLista() {
        initComponents();
        conexion = new ConexionMySQL("root", "", "spotydam"); //Editar nombre base de datos aqui
        controlador = new ControladorCanciones(conexion);
    }

    VentanaLista(LoginPage paginaLog) {
        initComponents();
        this.paginaLog = paginaLog;
        conexion = new ConexionMySQL("root", "", "spotydam"); //Editar nombre base de datos aqui
        controlador = new ControladorCanciones(conexion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        playButton = new javax.swing.JButton();
        insertButton = new javax.swing.JButton();
        showButton = new javax.swing.JButton();
        disconnectButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("CARGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        playButton.setText("PLAY");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        insertButton.setText("INSERTAR");
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        showButton.setText("MOSTRAR");
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });

        disconnectButton.setText("DESCARGAR");
        disconnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Título", "Álbum", "Artista", "Duración"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(playButton)
                        .addGap(18, 18, 18)
                        .addComponent(insertButton)
                        .addGap(18, 18, 18)
                        .addComponent(showButton)
                        .addGap(18, 18, 18)
                        .addComponent(disconnectButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(playButton)
                    .addComponent(insertButton)
                    .addComponent(showButton)
                    .addComponent(disconnectButton))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            conexion.conectar();
            JOptionPane.showMessageDialog(null, "Has cargado la PlayList", "Conectado", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VentanaLista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
        try {
            ArrayList<Cancion> lista = controlador.obtenerCanciones();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int fila = 0, columna = 0;
            for (Cancion song : lista) {
                model.setRowCount(model.getRowCount() + 1);
                model.setValueAt(song.getTitle(), fila, columna);
                model.setValueAt(song.getAlbum(), fila, columna + 1);
                model.setValueAt(song.getArtist(), fila, columna + 2);
                model.setValueAt(song.getDuration(), fila, columna + 3);
                fila++;
                columna = 0;
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Tienes que conectarte a la Base De Datos", "Error", JOptionPane.ERROR);
        }
    }//GEN-LAST:event_showButtonActionPerformed

    private void disconnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectButtonActionPerformed
        try {
            conexion.desconectar();
            JOptionPane.showMessageDialog(null, "Te has desconectado de la PlayList", "Desconectado", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_disconnectButtonActionPerformed

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        String title = JOptionPane.showInputDialog("Introduce el titulo");
        if (!title.isEmpty()) {
            String album = JOptionPane.showInputDialog("Introduce el album");
            if (!album.isEmpty()) {
                String artist = JOptionPane.showInputDialog("Introduce el artista");
                if (!artist.isEmpty()) {
                    String duration = JOptionPane.showInputDialog("Introduce la duracion (m:s)");
                    if (!duration.isEmpty()) {
                        String consulta = "INSERT INTO songs (Título,Álbum,Artista,Duración) VALUES ('" + title + "','" + album + "','" + artist + "','" + duration + "')";

                        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                        try {
                            conexion.ejecutarInsertDeleteUpdate(consulta);
                            JOptionPane.showMessageDialog(null, "Objeto insertado correctamente", "Objeto insertado", JOptionPane.INFORMATION_MESSAGE);
                            model.setRowCount(0);
                            showButtonActionPerformed(evt);
                        } catch (SQLException ex) {
                            System.out.println("No se puede añadir la cancion");
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "No se ha introducito ninguna duración", "Duración no válida", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "No se ha introducito ningún artista", "Artista no válido", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "No se ha introducito ningún album", "Album no válido", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se ha introducito ningún título", "Título no válido", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_insertButtonActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        ventanaReproducir = new VentanaReproducir(this);
        ventanaReproducir.setVisible(true);
    }//GEN-LAST:event_playButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton disconnectButton;
    private javax.swing.JButton insertButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton playButton;
    private javax.swing.JButton showButton;
    // End of variables declaration//GEN-END:variables
}
